### ISSUE TITLE
exodor?

### ISSUE THREAD

**Issue by Otakuzu** [SerenTera/monster-marker#10]
update to work with exodor rare mobs?

**Comment by maryannew** [comment]
> update to work with exodor rare mobs?

in  >>config.json add
		"2020_1600": "Red-Flecked Crab",
		"2020_1601": "Eyestalker",
		"2020_1100": "Elit Naga Mid",
		"2020_1101": "Sud",
		"2020_1102": "Nord",
		"2020_1200": "Priest",
		"2020_1300": "Manuk",
		"2020_1400": "Axcellob",
		"2020_1500": "Zemces",
		"2020_1201": "Kn",
		"2020_1202": "exe",		
		"2020_1700": "Vekes",

**Comment by Otakuzu** [comment]
thank you very much
    El sábado, 7 de diciembre de 2019 08:18:02 ART, maryannew <notifications@github.com> escribió:  
 
 

update to work with exodor rare mobs?


in >>config.json add
"2020_1600": "Red-Flecked Crab",
"2020_1601": "Eyestalker",
"2020_1100": "Elit Naga Mid",
"2020_1101": "Sud",
"2020_1102": "Nord",
"2020_1200": "Priest",
"2020_1300": "Manuk",
"2020_1400": "Axcellob",
"2020_1500": "Zemces",
"2020_1201": "Kn",
"2020_1202": "exe",
"2020_1700": "Vekes",

**Comment by Otakuzu** [comment]
thank you very much
