### ISSUE TITLE
Updating warn system to other event spawns

### ISSUE THREAD

**Issue by ACI-Translation** [SerenTera/monster-marker#2]
Hi, I was trying to change the module today to also mark bee spawns from the EU event. The problem is I don't know how I could get the mobzone and mobtemplate IDs from the game, so I was wondering if you could point me in the right direction.

**Comment by SerenTera** [comment]
Im not from eu and will not have pc access till friday, so i wont be able to help much. However u can try this:

Hook all sSpawnNpc and check the huntingzoneid differences 1st, since that is a very obvious telltale sign as the bee would be of a different zone than other local mobs.

**Comment by SerenTera** [comment]
Btw if the bees move even the slightest then the module will actually fail alot since it currently based on mob location instead of id. Keep in mind this is written 1month ago when i didnt even know how to code properly and just self taught myself js so you can expect lots of bugs here and there :/ i might rewrite it soon tho :(

**Comment by ACI-Translation** [comment]
Dang, a friend of mine was looking around and got a similar suggestion to hook s_spawn_npc but he never found out what this hooking actually meant. I assume i should use a packet sniffer for it but maybe there is some basic tool for this im not aware of?

Also the bees seem completely static so i have good hopes for it working, even if it were buggy the utility of knowing how to adapt it will be very welcome.

**Comment by SerenTera** [comment]
U can try using the logger module i have and then use !logger S_Spawn_User followed by !logger start 50 once u r near a bee. Make sure u move away and reload the bee to log the spawning packet. A json file will be generated in tge module folder which u can open with notepad++ to compare the ids.

**Comment by SerenTera** [comment]
I mean S_SPAWN_NPC

**Comment by ACI-Translation** [comment]
Yay, it took a few tries and some embarrassing mistakes to actually get the marker module working but since we weren't stumped how to even hook we got through it eventually \o/.
Here's a picture of the thing in action :P https://u.nya.is/xfhzrz.jpg

The bees do move a bit sometimes, which I believe is causing the markers not to despawn when they are killed, but since there's a flush function already built in it's not the end of the world.
Thanks again for your help friend!

**Comment by SerenTera** [comment]
no problems :) i might just rewrite the whole thing to use id instead so they will definitely despawn the markers, if i find the time to do so
